export default {
    path:"/cinema",
    name:"cinema",
    meta:{
        header:true,
        flooter:true
    },
    component:()=>import("../../pages/cinema/index.vue"),
    children:[
        {
            path:"/cinema",
           redireect:"/cinema/left",
           meta:{
            header:true,
            flooter:true,
            btn:false
        },
        },
        {
            path:"left",
            name:"left",
            meta:{
                header:true,
                flooter:true,
                btn:false
            },
            component:()=>import("../../components/left/index.vue")
        },
        {
            path:"right",
            name:"right",
            meta:{
                header:true,
                flooter:true,
                btn:false
            },
            component:()=>import("../../components/right/index.vue")
        },
    ]
}